
Waterloo_1:
   im_dirL: /home/user/Desktop/WaterlooIVC3DPhaseI/3D/Session3DIQ/
   im_dirR: /home/user/Desktop/WaterlooIVC3DPhaseI/3D/Session3DIQ/
patch_size: 32
stride: 32

train_ratio: 0.8
test_ratio: 0.2
