
Waterloo_1:
   im_dirL: /home/oussama.messai/Desktop/LIRIS_desk/Databases/3D Databases/IVC3D Canada Waterloo/WaterlooIVC3DPhaseI/WaterlooIVC3DPhaseI/3D/Session3DIQ/ #/home/user/Desktop/WaterlooIVC3DPhaseI/3D/Session3DIQ/
   im_dirR: /home/oussama.messai/Desktop/LIRIS_desk/Databases/3D Databases/IVC3D Canada Waterloo/WaterlooIVC3DPhaseI/WaterlooIVC3DPhaseI/3D/Session3DIQ/ #/home/user/Desktop/WaterlooIVC3DPhaseI/3D/Session3DIQ/

Waterloo_2:
   im_dirL: /home/oussama.messai/Desktop/LIRIS_desk/Databases/3D Databases/IVC3D Canada Waterloo/WaterlooIVC3DPhaseII/WaterlooIVC3DPhaseII/3D/Session3DIQ/
   im_dirR: /home/oussama.messai/Desktop/LIRIS_desk/Databases/3D Databases/IVC3D Canada Waterloo/WaterlooIVC3DPhaseII/WaterlooIVC3DPhaseII/3D/Session3DIQ/

patch_size: 32
stride: 32

train_ratio: 0.8
test_ratio: 0.2
